# NOTE:
# The following code was generated by "tools/generate.py" in the upstream Rust crate.
# Do not edit directly.

module Bidi
  module CharData
    # Represents values of the Unicode character property
    # [`Bidi_Class`](http://www.unicode.org/reports/tr44/#Bidi_Class), also
    # known as the *bidirectional character type*.
    #
    # * <http://www.unicode.org/reports/tr9/#Bidirectional_Character_Types>
    # * <http://www.unicode.org/reports/tr44/#Bidi_Class_Values>
    enum BidiClass
      # Arabic Letter
      AL
      # Arabic Number
      AN
      # Paragraph Separator
      B
      # Boundary Neutral
      BN
      # Common Separator
      CS
      # European Number
      EN
      # European Separator
      ES
      # European Terminator
      ET
      # First Strong Isolate
      FSI
      # Left-to-Right
      L
      # Left-to-Right Embedding
      LRE
      # Left-to-Right Isolate
      LRI
      # Left-to-Right Override
      LRO
      # Nonspacing Mark
      NSM
      # Other Neutral
      ON
      # Pop Directional Format
      PDF
      # Pop Directional Isolate
      PDI
      # Right-to-Left
      R
      # Right-to-Left Embedding
      RLE
      # Right-to-Left Isolate
      RLI
      # Right-to-Left Override
      RLO
      # Segment Separator
      S
      # White Space
      WS

      # Check if this character is removed by rule X9
      # <http://www.unicode.org/reports/tr9/#X9>
      def removed_by_x9? : Bool
        case self
        when RLE, LRE, RLO, LRO, PDF, BN
          true
        else
          false
        end
      end

      # Check if this character is not removed by rule X9
      def not_removed_by_x9? : Bool
        !removed_by_x9?
      end
    end

    # The [Unicode version](http://www.unicode.org/versions/) of data
    UNICODE_VERSION = {16_u64, 0_u64, 0_u64}
  end
end
