# Ameba configuration for PDFBox Crystal port

# Exclude spec files from all checks
exclude:
  - "spec"
  - "lib"

Metrics/CyclomaticComplexity:
  Excluded:
    - "src/fontbox/afm/parser.cr"  # parse_font_metric: 36, parse_char_metric: 17
    - "src/fontbox/cff/cff_parser.cr"  # read_real_number: 14, parse_font: 16
    - "src/fontbox/cff/type1_char_string.cr"  # handle_type1_command: 39
    - "src/fontbox/cff/type2_char_string.cr"  # convert_type2_command: 28, add_curve: 15
    - "src/fontbox/cff/type2_char_string_parser.cr"  # parse_sequence: 15
    - "src/fontbox/cmap/cmap_parser.cr"  # parse: 14, parse_literal_name: 24, parse_beginbfrange: 22, parse_next_token: 16, read_dictionary: 17
    - "src/fontbox/pfb/pfb_parser.cr"  # parse_pfb: 19
    - "src/fontbox/ttf/ttf_parser.cr"  # parse_table_headers: 15, read_table_directory: 20
    - "src/fontbox/ttf/ttf_subsetter.cr"  # add_compound_references: 17
    - "src/fontbox/ttf/ttf_tables.cr"  # read: 19, process_subtype12: 13, process_subtype13: 14
    - "src/fontbox/type1/type1_lexer.cr"  # read_token: 24, try_read_number: 21, read_regular: 14, read_string: 16
    - "src/fontbox/util/path.cr"  # compute_bounds: 17
    - "src/pdfbox/pdf_parser/base_parser.cr"  # end_of_name?: 16, read_literal_string: 32, read_number: 21, read_hexadecimal_string: 15
    - "src/pdfbox/pdf_parser/brute_force_parser.cr"  # bf_search_for_objects: 17, bf_search_for_obj_stream_offsets: 26, bf_search_for_trailer: 22
    - "src/pdfbox/pdf_parser/cos_parser.cr"  # parse_dir_object: 18, read_until_end_of_cos_dictionary: 18, parse_array: 15, read_until_end_stream: 16, parse_cos_stream: 13
    - "src/pdfbox/pdf_parser/endstream_filter_stream.cr"  # filter: 18
    - "src/pdfbox/pdf_parser/parser.cr"  # parse_xref: 31, parse_xref_stream: 13, parse_object_header_incremental: 13, resolve_object: 13, decode_stream_data: 13, apply_png_predictor_up_fast: 13, parse_catalog_from_trailer: 19, parse: 22
    - "src/pdfbox/pdf_parser/pdf_stream_parser.cr"  # parse_next_token: 19, parse_cos_number: 15, has_no_following_bin_data?: 35, read_operator: 17
    - "src/pdfbox/pdf_parser/pdf_xref_stream_parser.cr"  # init_parser_values: 16
    - "src/pdfbox/filter/run_length_decode_filter.cr"  # encode(io, io): 13
    - "src/pdfbox/pdf_parser/xref_parser.cr"  # parse_xref: 18, parse_xref_table: 18, find_object_key: 15
    - "src/pdfbox/pdf_parser/pdf_io.cr"  # parse_date_from_random_access_read: 34
    - "src/pdfbox/pdmodel/common/function/pdfunction.cr"  # create: 13
